// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorSafe.Backend.Data;

#nullable disable

namespace MotorSafe.Backend.Migrations
{
    [DbContext(typeof(MotorSafeDbContext))]
    [Migration("20260314130851_UpdateMechanicsSeedData")]
    partial class UpdateMechanicsSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MotorSafe.Backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("LocationLat")
                        .HasColumnType("double");

                    b.Property<double>("LocationLng")
                        .HasColumnType("double");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MechanicId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.Mechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SpecialSkills")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mechanics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Nguyễn Văn Linh, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.059999999999999,
                            Longitude = 108.20999999999999,
                            Name = "Nguyễn Văn An",
                            Phone = "0901000001",
                            Rating = 4.7999999999999998,
                            ShopName = "An Motor Repair",
                            SpecialSkills = "Engine, Tires"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Lê Duẩn, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.068000000000001,
                            Longitude = 108.22,
                            Name = "Trần Văn Bình",
                            Phone = "0901000002",
                            Rating = 4.5,
                            ShopName = "Bình Quick Fix",
                            SpecialSkills = "Battery, Start"
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Trần Phú, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.055,
                            Longitude = 108.205,
                            Name = "Lê Thị Cẩm",
                            Phone = "0901000003",
                            Rating = 4.9000000000000004,
                            ShopName = "Cẩm Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 4,
                            Address = "23 Hùng Vương, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.062000000000001,
                            Longitude = 108.215,
                            Name = "Phạm Hữu Đức",
                            Phone = "0901000004",
                            Rating = 4.2000000000000002,
                            ShopName = "Đức Sửa Xe",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 5,
                            Address = "56 Phan Châu Trinh, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.07,
                            Longitude = 108.212,
                            Name = "Võ Minh Em",
                            Phone = "0901000005",
                            Rating = 4.5999999999999996,
                            ShopName = "Em Motor",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 6,
                            Address = "89 Bạch Đằng, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.058,
                            Longitude = 108.208,
                            Name = "Hoàng Văn Phú",
                            Phone = "0901000006",
                            Rating = 4.7000000000000002,
                            ShopName = "Phú Auto Fix",
                            SpecialSkills = "Battery, Engine"
                        },
                        new
                        {
                            Id = 7,
                            Address = "34 Ông Ích Khiêm, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.065000000000001,
                            Longitude = 108.203,
                            Name = "Đỗ Quang Giang",
                            Phone = "0901000007",
                            Rating = 4.2999999999999998,
                            ShopName = "Giang Bike Care",
                            SpecialSkills = "Chain, Tires"
                        },
                        new
                        {
                            Id = 8,
                            Address = "67 Núi Thành, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.053000000000001,
                            Longitude = 108.218,
                            Name = "Ngô Thanh Hải",
                            Phone = "0901000008",
                            Rating = 4.4000000000000004,
                            ShopName = "Hải Motor Pro",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 9,
                            Address = "12 Hoàng Diệu, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.071999999999999,
                            Longitude = 108.206,
                            Name = "Bùi Văn Inh",
                            Phone = "0901000009",
                            Rating = 4.0999999999999996,
                            ShopName = "Inh Quick Repair",
                            SpecialSkills = "Tires"
                        },
                        new
                        {
                            Id = 10,
                            Address = "90 Điện Biên Phủ, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.065999999999999,
                            Longitude = 108.19799999999999,
                            Name = "Lý Minh Khang",
                            Phone = "0901000010",
                            Rating = 4.7999999999999998,
                            ShopName = "Khang Motor Shop",
                            SpecialSkills = "Engine, Battery"
                        },
                        new
                        {
                            Id = 11,
                            Address = "45 Hải Phòng, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.064,
                            Longitude = 108.2,
                            Name = "Trương Văn Long",
                            Phone = "0901000011",
                            Rating = 4.0,
                            ShopName = "Long Sửa Xe 24h",
                            SpecialSkills = "Chain"
                        },
                        new
                        {
                            Id = 12,
                            Address = "78 Đống Đa, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.059000000000001,
                            Longitude = 108.196,
                            Name = "Đinh Quốc Minh",
                            Phone = "0901000012",
                            Rating = 4.5,
                            ShopName = "Minh Auto Care",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 13,
                            Address = "23 Trần Cao Vân, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.071000000000002,
                            Longitude = 108.202,
                            Name = "Phan Hồng Nam",
                            Phone = "0901000013",
                            Rating = 4.5999999999999996,
                            ShopName = "Nam Bike Repair",
                            SpecialSkills = "Engine, Tires"
                        },
                        new
                        {
                            Id = 14,
                            Address = "56 Lê Thanh Nghị, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.053999999999998,
                            Longitude = 108.214,
                            Name = "Mai Xuân Oanh",
                            Phone = "0901000014",
                            Rating = 4.2999999999999998,
                            ShopName = "Oanh Motor Fix",
                            SpecialSkills = "Battery"
                        },
                        new
                        {
                            Id = 15,
                            Address = "89 Nguyễn Tri Phương, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.067,
                            Longitude = 108.20399999999999,
                            Name = "Cao Văn Phong",
                            Phone = "0901000015",
                            Rating = 4.7000000000000002,
                            ShopName = "Phong Express Repair",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 16,
                            Address = "12 Lê Đình Lý, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.061,
                            Longitude = 108.21599999999999,
                            Name = "Hồ Quang Quý",
                            Phone = "0901000016",
                            Rating = 4.2000000000000002,
                            ShopName = "Quý Bike Pro",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 17,
                            Address = "34 Nguyễn Hữu Thọ, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.048999999999999,
                            Longitude = 108.211,
                            Name = "Đặng Văn Rạng",
                            Phone = "0901000017",
                            Rating = 4.9000000000000004,
                            ShopName = "Rạng Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 18,
                            Address = "67 Xô Viết Nghệ Tĩnh, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.056999999999999,
                            Longitude = 108.209,
                            Name = "Vũ Đình Sơn",
                            Phone = "0901000018",
                            Rating = 4.4000000000000004,
                            ShopName = "Sơn Speed Fix",
                            SpecialSkills = "Battery, Tires"
                        },
                        new
                        {
                            Id = 19,
                            Address = "90 Trưng Nữ Vương, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.062999999999999,
                            Longitude = 108.20699999999999,
                            Name = "Lê Văn Tâm",
                            Phone = "0901000019",
                            Rating = 4.5999999999999996,
                            ShopName = "Tâm Motor 365",
                            SpecialSkills = "Chain, Engine"
                        },
                        new
                        {
                            Id = 20,
                            Address = "23 Yên Bái, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.068999999999999,
                            Longitude = 108.21299999999999,
                            Name = "Nguyễn Hữu Uy",
                            Phone = "0901000020",
                            Rating = 4.0999999999999996,
                            ShopName = "Uy Sửa Xe Nhanh",
                            SpecialSkills = "Tires"
                        },
                        new
                        {
                            Id = 21,
                            Address = "56 Thái Phiên, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.052,
                            Longitude = 108.21899999999999,
                            Name = "Trần Minh Vượng",
                            Phone = "0901000021",
                            Rating = 4.7999999999999998,
                            ShopName = "Vượng Auto",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 22,
                            Address = "78 Pasteur, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.074000000000002,
                            Longitude = 108.205,
                            Name = "Phạm Đức Xuyên",
                            Phone = "0901000022",
                            Rating = 4.2999999999999998,
                            ShopName = "Xuyên Motor Shop",
                            SpecialSkills = "Engine, Battery"
                        },
                        new
                        {
                            Id = 23,
                            Address = "12 Lý Tự Trọng, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.056000000000001,
                            Longitude = 108.20099999999999,
                            Name = "Võ Trung Yên",
                            Phone = "0901000023",
                            Rating = 4.5,
                            ShopName = "Yên Bike Fix",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 24,
                            Address = "34 Nguyễn Chí Thanh, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.065000000000001,
                            Longitude = 108.217,
                            Name = "Hoàng Trọng Anh",
                            Phone = "0901000024",
                            Rating = 4.7000000000000002,
                            ShopName = "Anh Phát Motor",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 25,
                            Address = "67 Đỗ Quang, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.050000000000001,
                            Longitude = 108.235,
                            Name = "Đỗ Ngọc Bảo",
                            Phone = "0901000025",
                            Rating = 4.2000000000000002,
                            ShopName = "Bảo Repair Center",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 26,
                            Address = "89 Lê Văn Hiến, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.047999999999998,
                            Longitude = 108.23,
                            Name = "Ngô Hải Châu",
                            Phone = "0901000026",
                            Rating = 4.5999999999999996,
                            ShopName = "Châu Motor Express",
                            SpecialSkills = "Battery"
                        },
                        new
                        {
                            Id = 27,
                            Address = "12 Nguyễn Văn Thoại, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.076000000000001,
                            Longitude = 108.22799999999999,
                            Name = "Bùi Đình Duy",
                            Phone = "0901000027",
                            Rating = 4.4000000000000004,
                            ShopName = "Duy Bike Care 24h",
                            SpecialSkills = "Tires"
                        },
                        new
                        {
                            Id = 28,
                            Address = "45 Phạm Văn Đồng, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.073,
                            Longitude = 108.232,
                            Name = "Lý Văn Đạt",
                            Phone = "0901000028",
                            Rating = 4.7999999999999998,
                            ShopName = "Đạt Motor Pro",
                            SpecialSkills = "Engine, Chain"
                        },
                        new
                        {
                            Id = 29,
                            Address = "78 An Nhơn, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.077999999999999,
                            Longitude = 108.22499999999999,
                            Name = "Trương Quốc Gia",
                            Phone = "0901000029",
                            Rating = 4.0,
                            ShopName = "Gia Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 30,
                            Address = "23 Ngô Quyền, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.074999999999999,
                            Longitude = 108.221,
                            Name = "Đinh Hữu Hào",
                            Phone = "0901000030",
                            Rating = 4.5,
                            ShopName = "Hào Quick Fix",
                            SpecialSkills = "Battery, Tires"
                        },
                        new
                        {
                            Id = 31,
                            Address = "56 Trần Đại Nghĩa, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.047000000000001,
                            Longitude = 108.226,
                            Name = "Phan Minh Khánh",
                            Phone = "0901000031",
                            Rating = 4.2999999999999998,
                            ShopName = "Khánh Sửa Xe",
                            SpecialSkills = "Chain"
                        },
                        new
                        {
                            Id = 32,
                            Address = "89 Mỹ An, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.050999999999998,
                            Longitude = 108.238,
                            Name = "Mai Trọng Lâm",
                            Phone = "0901000032",
                            Rating = 4.7000000000000002,
                            ShopName = "Lâm Motor Fix",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 33,
                            Address = "12 Võ Nguyên Giáp, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.068999999999999,
                            Longitude = 108.23999999999999,
                            Name = "Cao Quang Mạnh",
                            Phone = "0901000033",
                            Rating = 4.0999999999999996,
                            ShopName = "Mạnh Bike Pro",
                            SpecialSkills = "Tires, Engine"
                        },
                        new
                        {
                            Id = 34,
                            Address = "34 Trần Hưng Đạo, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.077000000000002,
                            Longitude = 108.215,
                            Name = "Hồ Đức Nghĩa",
                            Phone = "0901000034",
                            Rating = 4.9000000000000004,
                            ShopName = "Nghĩa Motor 24h",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 35,
                            Address = "67 Nguyễn Công Trứ, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.079999999999998,
                            Longitude = 108.218,
                            Name = "Đặng Minh Phúc",
                            Phone = "0901000035",
                            Rating = 4.4000000000000004,
                            ShopName = "Phúc Auto Repair",
                            SpecialSkills = "Battery, Chain"
                        },
                        new
                        {
                            Id = 36,
                            Address = "90 Nguyễn Lương Bằng, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.082000000000001,
                            Longitude = 108.155,
                            Name = "Vũ Hồng Quân",
                            Phone = "0901000036",
                            Rating = 4.5999999999999996,
                            ShopName = "Quân Motor Express",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 37,
                            Address = "23 Tôn Đức Thắng, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.085000000000001,
                            Longitude = 108.16,
                            Name = "Lê Quốc Sang",
                            Phone = "0901000037",
                            Rating = 4.2000000000000002,
                            ShopName = "Sang Bike Center",
                            SpecialSkills = "Tires"
                        },
                        new
                        {
                            Id = 38,
                            Address = "56 Hoàng Văn Thái, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.077999999999999,
                            Longitude = 108.16500000000001,
                            Name = "Nguyễn Tấn Tài",
                            Phone = "0901000038",
                            Rating = 4.7999999999999998,
                            ShopName = "Tài Motor Shop",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 39,
                            Address = "78 Nguyễn Sinh Sắc, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.071999999999999,
                            Longitude = 108.17,
                            Name = "Trần Hữu Vĩnh",
                            Phone = "0901000039",
                            Rating = 4.2999999999999998,
                            ShopName = "Vĩnh Sửa Xe Pro",
                            SpecialSkills = "Chain, Battery"
                        },
                        new
                        {
                            Id = 40,
                            Address = "12 Nguyễn Tất Thành, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.09,
                            Longitude = 108.15000000000001,
                            Name = "Phạm Quang Huy",
                            Phone = "0901000040",
                            Rating = 4.5,
                            ShopName = "Huy Motor Fix",
                            SpecialSkills = "Engine, Tires"
                        },
                        new
                        {
                            Id = 41,
                            Address = "34 Cách Mạng T8, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.039999999999999,
                            Longitude = 108.20999999999999,
                            Name = "Võ Thanh Liêm",
                            Phone = "0901000041",
                            Rating = 4.7000000000000002,
                            ShopName = "Liêm Bike Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 42,
                            Address = "67 Âu Cơ, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.038,
                            Longitude = 108.205,
                            Name = "Hoàng Minh Đạo",
                            Phone = "0901000042",
                            Rating = 4.0,
                            ShopName = "Đạo Quick Repair",
                            SpecialSkills = "Battery"
                        },
                        new
                        {
                            Id = 43,
                            Address = "89 Trường Chinh, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.035,
                            Longitude = 108.2,
                            Name = "Đỗ Văn Kiên",
                            Phone = "0901000043",
                            Rating = 4.5999999999999996,
                            ShopName = "Kiên Motor 365",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 44,
                            Address = "23 Tùng Thiện Vương, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.042000000000002,
                            Longitude = 108.215,
                            Name = "Ngô Đình Lộc",
                            Phone = "0901000044",
                            Rating = 4.4000000000000004,
                            ShopName = "Lộc Motor Care",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 45,
                            Address = "56 Võ Văn Kiệt, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.036999999999999,
                            Longitude = 108.22,
                            Name = "Bùi Trọng Nhân",
                            Phone = "0901000045",
                            Rating = 4.7999999999999998,
                            ShopName = "Nhân Express Motor",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 46,
                            Address = "78 Nguyễn Phước Lan, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.044,
                            Longitude = 108.22499999999999,
                            Name = "Lý Đình Phát",
                            Phone = "0901000046",
                            Rating = 4.0999999999999996,
                            ShopName = "Phát Bike Fix",
                            SpecialSkills = "Battery, Engine"
                        },
                        new
                        {
                            Id = 47,
                            Address = "12 Lê Trọng Tấn, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.045999999999999,
                            Longitude = 108.19499999999999,
                            Name = "Trương Văn Tín",
                            Phone = "0901000047",
                            Rating = 4.5,
                            ShopName = "Tín Sửa Xe 24h",
                            SpecialSkills = "Tires"
                        },
                        new
                        {
                            Id = 48,
                            Address = "34 Trần Đức Thảo, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.058,
                            Longitude = 108.22199999999999,
                            Name = "Đinh Xuân Việt",
                            Phone = "0901000048",
                            Rating = 4.9000000000000004,
                            ShopName = "Việt Motor Pro",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 49,
                            Address = "67 Nguyễn Du, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.062000000000001,
                            Longitude = 108.199,
                            Name = "Phan Đức Anh",
                            Phone = "0901000049",
                            Rating = 4.2999999999999998,
                            ShopName = "Anh Tú Motor",
                            SpecialSkills = "Chain"
                        },
                        new
                        {
                            Id = 50,
                            Address = "90 Duy Tân, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.053999999999998,
                            Longitude = 108.20399999999999,
                            Name = "Mai Hoàng Bách",
                            Phone = "0901000050",
                            Rating = 4.7000000000000002,
                            ShopName = "Bách Motor Center",
                            SpecialSkills = "Engine, Tires, Battery"
                        });
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cccd")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.Booking", b =>
                {
                    b.HasOne("MotorSafe.Backend.Models.User", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorSafe.Backend.Models.Mechanic", "Mechanic")
                        .WithMany("Bookings")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.Mechanic", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
