// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorSafe.Backend.Data;

#nullable disable

namespace MotorSafe.Backend.Migrations
{
    [DbContext(typeof(MotorSafeDbContext))]
    [Migration("20260316125926_AddRoleAndHelpers")]
    partial class AddRoleAndHelpers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MotorSafe.Backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("LocationLat")
                        .HasColumnType("double");

                    b.Property<double>("LocationLng")
                        .HasColumnType("double");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MechanicId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.Mechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SpecialSkills")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mechanics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "144 Bạch Đằng, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.039693,
                            Longitude = 108.207701,
                            Name = "Trần Văn Hùng",
                            Phone = "0902266383",
                            Rating = 4.5999999999999996,
                            Role = "Mechanic",
                            ShopName = "Dũng Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 2,
                            Address = "76 Lê Duẩn, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.07141,
                            Longitude = 108.187268,
                            Name = "Dương Văn Cường",
                            Phone = "0907010156",
                            Rating = 4.5999999999999996,
                            Role = "Mechanic",
                            ShopName = "Phú Motor Service",
                            SpecialSkills = "Battery, Engine"
                        },
                        new
                        {
                            Id = 3,
                            Address = "189 Nguyễn Tri Phương, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.071504000000001,
                            Longitude = 108.195036,
                            Name = "Đặng Công Phong",
                            Phone = "0901805365",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "Phong Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 4,
                            Address = "137 Hoàng Diệu, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.035803000000001,
                            Longitude = 108.19898000000001,
                            Name = "Vũ Đình Minh",
                            Phone = "0901081922",
                            Rating = 4.2000000000000002,
                            Role = "Mechanic",
                            ShopName = "Tâm Motor Service",
                            SpecialSkills = "Chain, Tires"
                        },
                        new
                        {
                            Id = 5,
                            Address = "195 Lê Duẩn, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.0425,
                            Longitude = 108.21868499999999,
                            Name = "Lý Quốc Nam",
                            Phone = "0906354693",
                            Rating = 4.5999999999999996,
                            Role = "Mechanic",
                            ShopName = "Giang Motor Service",
                            SpecialSkills = "Battery"
                        },
                        new
                        {
                            Id = 6,
                            Address = "27 Hùng Vương, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.044758999999999,
                            Longitude = 108.236181,
                            Name = "Ngô Ngọc Nam",
                            Phone = "0907535371",
                            Rating = 4.4000000000000004,
                            Role = "Mechanic",
                            ShopName = "Phú Motor Service",
                            SpecialSkills = "Battery, Engine"
                        },
                        new
                        {
                            Id = 7,
                            Address = "89 Hùng Vương, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.059097000000001,
                            Longitude = 108.198215,
                            Name = "Đặng Thu Phương Phú",
                            Phone = "0904558472",
                            Rating = 4.2000000000000002,
                            Role = "Mechanic",
                            ShopName = "Hùng Motor Service",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 8,
                            Address = "69 Phạm Văn Đồng, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.072583999999999,
                            Longitude = 108.182838,
                            Name = "Hồ Thành An",
                            Phone = "0906325015",
                            Rating = 4.9000000000000004,
                            Role = "Mechanic",
                            ShopName = "Phát Motor Service",
                            SpecialSkills = "Chain, Tires"
                        },
                        new
                        {
                            Id = 9,
                            Address = "153 Hùng Vương, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.050722,
                            Longitude = 108.19533,
                            Name = "Trần Quang An",
                            Phone = "0902252554",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "Khánh Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 10,
                            Address = "174 Phạm Văn Đồng, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.040134999999999,
                            Longitude = 108.192561,
                            Name = "Đặng Công Khánh",
                            Phone = "0902181530",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "Phát Motor Service",
                            SpecialSkills = "Battery"
                        },
                        new
                        {
                            Id = 11,
                            Address = "94 Trần Phú, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.075185999999999,
                            Longitude = 108.194344,
                            Name = "Hồ Quang Phú",
                            Phone = "0907368463",
                            Rating = 4.2999999999999998,
                            Role = "Mechanic",
                            ShopName = "Giang Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 12,
                            Address = "40 Hùng Vương, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.058599000000001,
                            Longitude = 108.181062,
                            Name = "Hồ Hữu Khánh",
                            Phone = "0906900481",
                            Rating = 4.7999999999999998,
                            Role = "Mechanic",
                            ShopName = "An Motor Service",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 13,
                            Address = "41 Phạm Văn Đồng, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.037997000000001,
                            Longitude = 108.201457,
                            Name = "Bùi Thu Phương Bảo",
                            Phone = "0906362140",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "Giang Motor Service",
                            SpecialSkills = "Start"
                        },
                        new
                        {
                            Id = 14,
                            Address = "200 Điện Biên Phủ, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.079957,
                            Longitude = 108.208333,
                            Name = "Dương Văn Phú",
                            Phone = "0906886917",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "Em Motor Service",
                            SpecialSkills = "Chain, Tires"
                        },
                        new
                        {
                            Id = 15,
                            Address = "72 Hùng Vương, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.039353999999999,
                            Longitude = 108.229726,
                            Name = "Phạm Công Long",
                            Phone = "0905527799",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "An Motor Service",
                            SpecialSkills = "Battery"
                        },
                        new
                        {
                            Id = 16,
                            Address = "31 Nguyễn Văn Linh, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.057452000000001,
                            Longitude = 108.223732,
                            Name = "Đỗ Đức Khánh",
                            Phone = "0904547342",
                            Rating = 4.0999999999999996,
                            Role = "Mechanic",
                            ShopName = "Giang Motor Service",
                            SpecialSkills = "Battery, Engine"
                        },
                        new
                        {
                            Id = 17,
                            Address = "31 Trần Phú, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.068100000000001,
                            Longitude = 108.20604899999999,
                            Name = "Võ Bích Phú",
                            Phone = "0903913619",
                            Rating = 4.5,
                            Role = "Mechanic",
                            ShopName = "Hùng Motor Service",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 18,
                            Address = "137 Phạm Văn Đồng, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.059002,
                            Longitude = 108.197163,
                            Name = "Bùi Thanh Nam",
                            Phone = "0909675901",
                            Rating = 4.2000000000000002,
                            Role = "Mechanic",
                            ShopName = "Long Motor Service",
                            SpecialSkills = "Battery, Engine"
                        },
                        new
                        {
                            Id = 19,
                            Address = "144 Nguyễn Văn Linh, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.057421999999999,
                            Longitude = 108.238657,
                            Name = "Bùi Đình Cường",
                            Phone = "0902676611",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "Khánh Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 20,
                            Address = "166 Nguyễn Văn Linh, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.074705999999999,
                            Longitude = 108.228442,
                            Name = "Dương Văn Bảo",
                            Phone = "0907875977",
                            Rating = 4.7999999999999998,
                            Role = "Mechanic",
                            ShopName = "Phong Motor Service",
                            SpecialSkills = "Tires"
                        },
                        new
                        {
                            Id = 21,
                            Address = "184 Điện Biên Phủ, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.072825999999999,
                            Longitude = 108.227031,
                            Name = "Đặng Đình Em",
                            Phone = "0901620795",
                            Rating = 4.2999999999999998,
                            Role = "Mechanic",
                            ShopName = "Long Motor Service",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 22,
                            Address = "83 Điện Biên Phủ, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.065102,
                            Longitude = 108.22833300000001,
                            Name = "Huỳnh Công Phong",
                            Phone = "0902435633",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "Khánh Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 23,
                            Address = "125 Võ Nguyên Giáp, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.057881999999999,
                            Longitude = 108.187048,
                            Name = "Đỗ Quốc Tâm",
                            Phone = "0906567681",
                            Rating = 4.0999999999999996,
                            Role = "Mechanic",
                            ShopName = "Phú Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 24,
                            Address = "134 Xô Viết Nghệ Tĩnh, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.041969000000002,
                            Longitude = 108.192632,
                            Name = "Bùi Hữu Cường",
                            Phone = "0901659822",
                            Rating = 4.0999999999999996,
                            Role = "Mechanic",
                            ShopName = "Khánh Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 25,
                            Address = "61 Xô Viết Nghệ Tĩnh, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.042446000000002,
                            Longitude = 108.182249,
                            Name = "Lý Thu Phương Tâm",
                            Phone = "0906728527",
                            Rating = 4.7999999999999998,
                            Role = "Mechanic",
                            ShopName = "An Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 26,
                            Address = "23 Phạm Văn Đồng, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.056607,
                            Longitude = 108.23739,
                            Name = "Phạm Thị Long",
                            Phone = "0902656516",
                            Rating = 4.4000000000000004,
                            Role = "Mechanic",
                            ShopName = "An Motor Service",
                            SpecialSkills = "Tires"
                        },
                        new
                        {
                            Id = 27,
                            Address = "48 Hùng Vương, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.077292,
                            Longitude = 108.218667,
                            Name = "Phạm Hữu Phong",
                            Phone = "0902375877",
                            Rating = 4.5999999999999996,
                            Role = "Mechanic",
                            ShopName = "Tâm Motor Service",
                            SpecialSkills = "Battery, Engine"
                        },
                        new
                        {
                            Id = 28,
                            Address = "78 Nguyễn Văn Linh, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.067958999999998,
                            Longitude = 108.213646,
                            Name = "Phạm Bích Nam",
                            Phone = "0901179426",
                            Rating = 4.2999999999999998,
                            Role = "Mechanic",
                            ShopName = "Phát Motor Service",
                            SpecialSkills = "Chain, Tires"
                        },
                        new
                        {
                            Id = 29,
                            Address = "60 Nguyễn Văn Linh, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.043433,
                            Longitude = 108.21571400000001,
                            Name = "Lê Ngọc Hùng",
                            Phone = "0903027034",
                            Rating = 4.0999999999999996,
                            Role = "Mechanic",
                            ShopName = "An Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 30,
                            Address = "110 Điện Biên Phủ, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.065874999999998,
                            Longitude = 108.21199300000001,
                            Name = "Bùi Quang Minh",
                            Phone = "0902086631",
                            Rating = 4.4000000000000004,
                            Role = "Mechanic",
                            ShopName = "Minh Motor Service",
                            SpecialSkills = "Tires"
                        },
                        new
                        {
                            Id = 31,
                            Address = "124 Hùng Vương, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.067799999999998,
                            Longitude = 108.22889499999999,
                            Name = "Đặng Bích Phong",
                            Phone = "0904480863",
                            Rating = 4.2000000000000002,
                            Role = "Mechanic",
                            ShopName = "An Motor Service",
                            SpecialSkills = "Chain, Tires"
                        },
                        new
                        {
                            Id = 32,
                            Address = "110 Võ Nguyên Giáp, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.059985999999999,
                            Longitude = 108.233859,
                            Name = "Lê Văn Long",
                            Phone = "0901780257",
                            Rating = 4.5,
                            Role = "Mechanic",
                            ShopName = "An Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 33,
                            Address = "177 Phạm Văn Đồng, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.051333,
                            Longitude = 108.23492299999999,
                            Name = "Lý Thu Phương Phú",
                            Phone = "0908052777",
                            Rating = 4.5,
                            Role = "Mechanic",
                            ShopName = "Nam Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 34,
                            Address = "167 Trần Phú, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.068887,
                            Longitude = 108.199265,
                            Name = "Dương Đức Nam",
                            Phone = "0903054708",
                            Rating = 4.0,
                            Role = "Mechanic",
                            ShopName = "Phong Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 35,
                            Address = "5 Nguyễn Văn Linh, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.040619,
                            Longitude = 108.224721,
                            Name = "Hồ Hữu Tâm",
                            Phone = "0903023226",
                            Rating = 4.0,
                            Role = "Mechanic",
                            ShopName = "Tâm Motor Service",
                            SpecialSkills = "Start"
                        },
                        new
                        {
                            Id = 36,
                            Address = "14 Phạm Văn Đồng, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.044208999999999,
                            Longitude = 108.19070000000001,
                            Name = "Huỳnh Quốc Khánh",
                            Phone = "0903331732",
                            Rating = 4.9000000000000004,
                            Role = "Mechanic",
                            ShopName = "An Motor Service",
                            SpecialSkills = "Engine"
                        },
                        new
                        {
                            Id = 37,
                            Address = "14 Phạm Văn Đồng, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.039021000000002,
                            Longitude = 108.22176,
                            Name = "Võ Văn Giang",
                            Phone = "0908418042",
                            Rating = 4.5999999999999996,
                            Role = "Mechanic",
                            ShopName = "Hùng Motor Service",
                            SpecialSkills = "Chain, Tires"
                        },
                        new
                        {
                            Id = 38,
                            Address = "1 Võ Nguyên Giáp, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.067371000000001,
                            Longitude = 108.225207,
                            Name = "Bùi Đức Tâm",
                            Phone = "0907155005",
                            Rating = 4.0999999999999996,
                            Role = "Mechanic",
                            ShopName = "Tâm Motor Service",
                            SpecialSkills = "Battery"
                        },
                        new
                        {
                            Id = 39,
                            Address = "35 Phạm Văn Đồng, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.077842,
                            Longitude = 108.207883,
                            Name = "Bùi Ngọc Phú",
                            Phone = "0909112165",
                            Rating = 4.7999999999999998,
                            Role = "Mechanic",
                            ShopName = "Minh Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 40,
                            Address = "77 Nguyễn Tri Phương, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.063880000000001,
                            Longitude = 108.18901200000001,
                            Name = "Phạm Công Phú",
                            Phone = "0901294561",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "Dũng Motor Service",
                            SpecialSkills = "Start"
                        },
                        new
                        {
                            Id = 41,
                            Address = "54 Hùng Vương, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.056736000000001,
                            Longitude = 108.227389,
                            Name = "Trần Ngọc Phát",
                            Phone = "0906373719",
                            Rating = 4.7000000000000002,
                            Role = "Mechanic",
                            ShopName = "Nam Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 42,
                            Address = "155 Hùng Vương, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.067795,
                            Longitude = 108.213497,
                            Name = "Đặng Công Khánh",
                            Phone = "0906015648",
                            Rating = 4.9000000000000004,
                            Role = "Mechanic",
                            ShopName = "An Motor Service",
                            SpecialSkills = "Tires"
                        },
                        new
                        {
                            Id = 43,
                            Address = "195 Nguyễn Tri Phương, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.064568999999999,
                            Longitude = 108.183446,
                            Name = "Đặng Quốc Nam",
                            Phone = "0901499039",
                            Rating = 4.0,
                            Role = "Mechanic",
                            ShopName = "Bảo Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 44,
                            Address = "4 Lê Duẩn, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.079637000000002,
                            Longitude = 108.236773,
                            Name = "Phạm Minh Tùng",
                            Phone = "0907359152",
                            Rating = 4.5999999999999996,
                            Role = "Mechanic",
                            ShopName = "Phú Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 45,
                            Address = "97 Lê Duẩn, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.051197999999999,
                            Longitude = 108.202752,
                            Name = "Trần Thanh Long",
                            Phone = "0906340362",
                            Rating = 5.0,
                            Role = "Mechanic",
                            ShopName = "Phát Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 46,
                            Address = "77 Hùng Vương, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.077242999999999,
                            Longitude = 108.239994,
                            Name = "Hồ Công Long",
                            Phone = "0902193307",
                            Rating = 4.0,
                            Role = "Mechanic",
                            ShopName = "Khánh Motor Service",
                            SpecialSkills = "All"
                        },
                        new
                        {
                            Id = 47,
                            Address = "40 Hùng Vương, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.077912999999999,
                            Longitude = 108.18360699999999,
                            Name = "Nguyễn Minh Bảo",
                            Phone = "0901467109",
                            Rating = 4.0999999999999996,
                            Role = "Mechanic",
                            ShopName = "Phú Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 48,
                            Address = "19 Hoàng Diệu, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.04917,
                            Longitude = 108.22680699999999,
                            Name = "Phạm Minh Minh",
                            Phone = "0903328041",
                            Rating = 4.5999999999999996,
                            Role = "Mechanic",
                            ShopName = "Phát Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 49,
                            Address = "106 Hùng Vương, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.052149,
                            Longitude = 108.184136,
                            Name = "Bùi Quốc Em",
                            Phone = "0902719388",
                            Rating = 4.7999999999999998,
                            Role = "Mechanic",
                            ShopName = "Bảo Motor Service",
                            SpecialSkills = "Tires, Chain"
                        },
                        new
                        {
                            Id = 50,
                            Address = "108 Phạm Văn Đồng, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.038305000000001,
                            Longitude = 108.197221,
                            Name = "Lý Đức Phát",
                            Phone = "0905337574",
                            Rating = 4.2999999999999998,
                            Role = "Mechanic",
                            ShopName = "Cường Motor Service",
                            SpecialSkills = "Battery"
                        },
                        new
                        {
                            Id = 51,
                            Address = "123 Điện Biên Phủ, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.059414,
                            Longitude = 108.20502500000001,
                            Name = "Võ Quốc Phát",
                            Phone = "0919163765",
                            Rating = 4.9000000000000004,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 52,
                            Address = "132 Nguyễn Văn Linh, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.073778999999998,
                            Longitude = 108.23536900000001,
                            Name = "Ngô Đình Em",
                            Phone = "0918373554",
                            Rating = 4.5,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 53,
                            Address = "67 Nguyễn Văn Linh, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.057155000000002,
                            Longitude = 108.232353,
                            Name = "Nguyễn Bích Phát",
                            Phone = "0915945527",
                            Rating = 4.7000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 54,
                            Address = "176 Trần Phú, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.057230000000001,
                            Longitude = 108.23022,
                            Name = "Vũ Quốc Hùng",
                            Phone = "0912281734",
                            Rating = 4.2999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 55,
                            Address = "158 Điện Biên Phủ, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.057365999999998,
                            Longitude = 108.19178100000001,
                            Name = "Đặng Thu Phương Nam",
                            Phone = "0914267295",
                            Rating = 4.7000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 56,
                            Address = "125 Phạm Văn Đồng, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.053754999999999,
                            Longitude = 108.21426700000001,
                            Name = "Phan Bích An",
                            Phone = "0911971754",
                            Rating = 4.4000000000000004,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 57,
                            Address = "95 Bạch Đằng, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.064686999999999,
                            Longitude = 108.190511,
                            Name = "Phạm Ngọc Phong",
                            Phone = "0914582901",
                            Rating = 4.5,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 58,
                            Address = "100 Võ Nguyên Giáp, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.054480000000002,
                            Longitude = 108.235135,
                            Name = "Dương Văn Khánh",
                            Phone = "0914733916",
                            Rating = 4.5,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 59,
                            Address = "194 Hoàng Diệu, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.050746,
                            Longitude = 108.19506800000001,
                            Name = "Lê Hữu Khánh",
                            Phone = "0919007596",
                            Rating = 4.0,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 60,
                            Address = "72 Hoàng Diệu, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.078218,
                            Longitude = 108.18853300000001,
                            Name = "Bùi Quốc Phong",
                            Phone = "0912296885",
                            Rating = 4.5999999999999996,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 61,
                            Address = "42 Hoàng Diệu, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.069638000000001,
                            Longitude = 108.20648199999999,
                            Name = "Nguyễn Thu Phương Cường",
                            Phone = "0915358134",
                            Rating = 4.5,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 62,
                            Address = "192 Hùng Vương, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.037642000000002,
                            Longitude = 108.237258,
                            Name = "Trần Minh Giang",
                            Phone = "0918769038",
                            Rating = 5.0,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 63,
                            Address = "47 Nguyễn Văn Linh, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.054141000000001,
                            Longitude = 108.220573,
                            Name = "Ngô Minh Phú",
                            Phone = "0919894813",
                            Rating = 4.2999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 64,
                            Address = "108 Lê Duẩn, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.070193,
                            Longitude = 108.213204,
                            Name = "Đỗ Đình Cường",
                            Phone = "0913662533",
                            Rating = 4.2999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 65,
                            Address = "183 Xô Viết Nghệ Tĩnh, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.070070000000001,
                            Longitude = 108.22863,
                            Name = "Phan Thu Phương Nam",
                            Phone = "0915900168",
                            Rating = 4.7000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 66,
                            Address = "30 Võ Nguyên Giáp, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.036237,
                            Longitude = 108.225917,
                            Name = "Lê Ngọc Phát",
                            Phone = "0919742510",
                            Rating = 4.9000000000000004,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 67,
                            Address = "122 Bạch Đằng, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.043025,
                            Longitude = 108.180026,
                            Name = "Phạm Thanh Tâm",
                            Phone = "0913349723",
                            Rating = 4.5,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 68,
                            Address = "73 Võ Nguyên Giáp, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.050298000000002,
                            Longitude = 108.203655,
                            Name = "Lê Quốc Cường",
                            Phone = "0912058147",
                            Rating = 4.7999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 69,
                            Address = "34 Nguyễn Văn Linh, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.075147000000001,
                            Longitude = 108.181404,
                            Name = "Bùi Thị Phong",
                            Phone = "0911350904",
                            Rating = 5.0,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 70,
                            Address = "99 Hoàng Diệu, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.064651999999999,
                            Longitude = 108.218411,
                            Name = "Phạm Công Tâm",
                            Phone = "0912002558",
                            Rating = 4.9000000000000004,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 71,
                            Address = "169 Hoàng Diệu, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.051475,
                            Longitude = 108.233063,
                            Name = "Lê Văn Minh",
                            Phone = "0912432341",
                            Rating = 4.4000000000000004,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 72,
                            Address = "191 Võ Nguyên Giáp, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.061025999999998,
                            Longitude = 108.19619,
                            Name = "Lý Văn Tâm",
                            Phone = "0919272279",
                            Rating = 4.2999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 73,
                            Address = "90 Trần Phú, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.058257999999999,
                            Longitude = 108.183408,
                            Name = "Phan Thị Dũng",
                            Phone = "0918967108",
                            Rating = 4.0999999999999996,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 74,
                            Address = "136 Hoàng Diệu, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.062428000000001,
                            Longitude = 108.20669599999999,
                            Name = "Trần Đình Phong",
                            Phone = "0912512763",
                            Rating = 4.5,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 75,
                            Address = "80 Lê Duẩn, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.073847000000001,
                            Longitude = 108.222731,
                            Name = "Nguyễn Quang Em",
                            Phone = "0919203900",
                            Rating = 4.5999999999999996,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 76,
                            Address = "72 Hoàng Diệu, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.051165000000001,
                            Longitude = 108.18458,
                            Name = "Bùi Thanh Minh",
                            Phone = "0917462271",
                            Rating = 4.9000000000000004,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 77,
                            Address = "156 Trần Phú, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.055077000000001,
                            Longitude = 108.234461,
                            Name = "Ngô Ngọc Tùng",
                            Phone = "0918116649",
                            Rating = 4.2999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 78,
                            Address = "28 Hùng Vương, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.071334,
                            Longitude = 108.206491,
                            Name = "Lý Thanh Phát",
                            Phone = "0914221696",
                            Rating = 4.7999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 79,
                            Address = "156 Võ Nguyên Giáp, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.042770999999998,
                            Longitude = 108.180347,
                            Name = "Vũ Quốc Nam",
                            Phone = "0916588046",
                            Rating = 4.2000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 80,
                            Address = "129 Hùng Vương, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.044336000000001,
                            Longitude = 108.198497,
                            Name = "Trần Hữu Dũng",
                            Phone = "0913599782",
                            Rating = 4.4000000000000004,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 81,
                            Address = "12 Điện Biên Phủ, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.059438,
                            Longitude = 108.22289499999999,
                            Name = "Hoàng Văn Phong",
                            Phone = "0917054828",
                            Rating = 4.5999999999999996,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 82,
                            Address = "87 Hùng Vương, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.055972000000001,
                            Longitude = 108.190065,
                            Name = "Huỳnh Bích Dũng",
                            Phone = "0912854055",
                            Rating = 4.4000000000000004,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 83,
                            Address = "11 Trần Phú, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.074818,
                            Longitude = 108.19972,
                            Name = "Nguyễn Thành Tâm",
                            Phone = "0911756616",
                            Rating = 4.2000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 84,
                            Address = "119 Hoàng Diệu, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.073687,
                            Longitude = 108.23871,
                            Name = "Đặng Thành Long",
                            Phone = "0919950124",
                            Rating = 4.7000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 85,
                            Address = "180 Phạm Văn Đồng, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.036111999999999,
                            Longitude = 108.229878,
                            Name = "Hồ Hữu Tâm",
                            Phone = "0911758945",
                            Rating = 4.2999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 86,
                            Address = "21 Điện Biên Phủ, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.047615,
                            Longitude = 108.237532,
                            Name = "Hồ Đình Giang",
                            Phone = "0911528625",
                            Rating = 4.2999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 87,
                            Address = "91 Bạch Đằng, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.048976,
                            Longitude = 108.216607,
                            Name = "Đặng Thu Phương Khánh",
                            Phone = "0916479534",
                            Rating = 4.7000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 88,
                            Address = "49 Lê Duẩn, Sơn Trà, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.077362000000001,
                            Longitude = 108.222936,
                            Name = "Vũ Thu Phương An",
                            Phone = "0919649882",
                            Rating = 4.2999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 89,
                            Address = "102 Trần Phú, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.067140999999999,
                            Longitude = 108.199051,
                            Name = "Ngô Ngọc Cường",
                            Phone = "0917718885",
                            Rating = 4.0,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 90,
                            Address = "160 Trần Phú, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.058098000000001,
                            Longitude = 108.227228,
                            Name = "Lý Thành Minh",
                            Phone = "0914935229",
                            Rating = 4.0999999999999996,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 91,
                            Address = "25 Lê Duẩn, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.045145999999999,
                            Longitude = 108.23985399999999,
                            Name = "Hoàng Thanh Phát",
                            Phone = "0915909051",
                            Rating = 4.2000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 92,
                            Address = "179 Nguyễn Tri Phương, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.052862000000001,
                            Longitude = 108.19986299999999,
                            Name = "Dương Công Phát",
                            Phone = "0915906856",
                            Rating = 4.7999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 93,
                            Address = "149 Hoàng Diệu, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.063476999999999,
                            Longitude = 108.188294,
                            Name = "Trần Minh Cường",
                            Phone = "0916495523",
                            Rating = 4.7999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 94,
                            Address = "75 Lê Duẩn, Liên Chiểu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.037096999999999,
                            Longitude = 108.22495600000001,
                            Name = "Dương Quang Khánh",
                            Phone = "0914185230",
                            Rating = 4.7000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 95,
                            Address = "126 Bạch Đằng, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.069326,
                            Longitude = 108.222104,
                            Name = "Bùi Quang Tâm",
                            Phone = "0911831883",
                            Rating = 4.5999999999999996,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 96,
                            Address = "117 Điện Biên Phủ, Ngũ Hành Sơn, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.069091,
                            Longitude = 108.18358499999999,
                            Name = "Lê Ngọc Giang",
                            Phone = "0916625078",
                            Rating = 4.0999999999999996,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 97,
                            Address = "191 Trần Phú, Thanh Khê, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.073036999999999,
                            Longitude = 108.184416,
                            Name = "Huỳnh Bích Dũng",
                            Phone = "0914365880",
                            Rating = 4.5999999999999996,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 98,
                            Address = "20 Võ Nguyên Giáp, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.069973000000001,
                            Longitude = 108.227374,
                            Name = "Lê Công Bảo",
                            Phone = "0918781035",
                            Rating = 4.0999999999999996,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 99,
                            Address = "56 Xô Viết Nghệ Tĩnh, Cẩm Lệ, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.035305999999999,
                            Longitude = 108.219342,
                            Name = "Dương Ngọc Phát",
                            Phone = "0915371787",
                            Rating = 4.7000000000000002,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        },
                        new
                        {
                            Id = 100,
                            Address = "41 Trần Phú, Hải Châu, Đà Nẵng",
                            IsAvailable = true,
                            Latitude = 16.058761000000001,
                            Longitude = 108.201759,
                            Name = "Lê Thị Tùng",
                            Phone = "0912265461",
                            Rating = 4.7999999999999998,
                            Role = "CommunityHelper",
                            ShopName = "Người hỗ trợ cộng đồng",
                            SpecialSkills = ""
                        });
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cccd")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.Booking", b =>
                {
                    b.HasOne("MotorSafe.Backend.Models.User", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotorSafe.Backend.Models.Mechanic", "Mechanic")
                        .WithMany("Bookings")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.Mechanic", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MotorSafe.Backend.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
